name: Build Tauri App

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          configPath: './tauri.conf.json'
          distPath: '../.output/public'
          iconPath: './icons/icon.ico'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
